Develop
openimis/openimis_django_openhim_mediators pull request #1
Opened 2021-02-25 05:24 UTC by davismutinda

2021-03-10 16:20 UTC, dragos-dobre commented
Please add __pycache__ folder in .gitignore to not include in the distribution. Then manually remove the committed __pycache__ folders from this repo. Thanks.

2021-03-10 17:30 UTC, dragos-dobre requested changes

2021-03-10 17:30 UTC, dragos-dobre commented on .gitignore
> -__pycache__/
Please keep this file as it is and remove the committed files that should be ignored.

2021-03-10 17:30 UTC, dragos-dobre commented on LICENSE
> -                    GNU AFFERO GENERAL PUBLIC LICENSE
Please keep this LICENSE file.

2021-03-31 12:46 UTC, delcroip approved these changes

2021-03-31 12:46 UTC, merged